# Generated by Django 4.2.6 on 2023-10-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_auth_status_user_auth_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfirmation',
            old_name='is_confired',
            new_name='is_confirmed',
        ),
    ]
